# $APPCENTER_NAME_ANDROID_PRODUCTION = The App Center project name for android e.g. Solid-State-Group/Hero-Wellbeing-Android
# $APPCENTER_NAME_ANDROID_STAGING = The App Center project name for android e.g. Solid-State-Group/Hero-Wellbeing-Android
# $APPCENTER_NAME_IOS_PRODUCTION = The App Center project name for ios e.g. Solid-State-Group/Hero-Wellbeing-iOS
# $APPCENTER_NAME_IOS_STAGING = The App Center project name for ios e.g. Solid-State-Group/Hero-Wellbeing-iOS-Staging
# APPCENTER_ACCESS_TOKEN = The token needed in order to use the appcenter cli in distribute-mobile.sh
# $CODE_PUSH_NAME_IOS = The AppCenter Project all iOS codepush builds go to e.g. Solid-State-Group/Hero-Wellbeing-iOS
# $CODE_PUSH_NAME_ANDROID = The AppCenter Project all iOS codepush builds go to e.g. Solid-State-Group/Hero-Wellbeing-iOS
# $NOW_TEAM_NAME - The vercel team name to deploy with e.g. solidstategroup
# $NOW_TOKEN - The vercel token to build web - https://vercel.com/account/tokens

stages:
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/


.web_deploy_common_required_changes: &web_deploy_common_required_changes
  changes:
    - "*"
    - common/**/*
    - components/**/*
    - pages/**/*
    - project/**/*
    - static/**/*
    - styles/**/*

.web_deploy_common_script: &web_deploy_common_script
  before_script:
    - npm i -g now
    - npm run env_script

deploy-web-production:
  image: mhart/alpine-node:10
  stage: deploy
  variables:
    ENV: prod
  <<: *web_deploy_common_script
  script:
    - now --token $NOW_TOKEN --scope $NOW_TEAM_NAME --confirm --local-config now.json --prod --build-env ENV=$ENV --name=$CI_PROJECT_NAME
  only:
    refs:
      - master
    <<: *web_deploy_common_required_changes
    variables:
      - $NOW_TOKEN
      - $NOW_TEAM_NAME

deploy-web-staging:
  image: mhart/alpine-node:10
  stage: deploy
  variables:
    ENV: staging
  <<: *web_deploy_common_script
  script:
    - url=$(now --token $NOW_TOKEN --scope $NOW_TEAM_NAME --confirm --local-config now.json --build-env ENV=$ENV --name=$CI_PROJECT_NAME)
    - now alias --token $NOW_TOKEN --scope $NOW_TEAM_NAME $url ${CI_PROJECT_NAME}-$CI_COMMIT_REF_SLUG
  only:
    refs:
      - staging
    <<: *web_deploy_common_required_changes
    variables:
      - $NOW_TOKEN
      - $NOW_TEAM_NAME

deploy-web-feature:
  image: mhart/alpine-node:10
  stage: deploy
  variables:
    ENV: dev
  <<: *web_deploy_common_script
  script:
    - url=$(now --token $NOW_TOKEN --scope $NOW_TEAM_NAME --confirm --local-config now.json --build-env ENV=$ENV --name=$CI_PROJECT_NAME)
    - now alias --token $NOW_TOKEN --scope $NOW_TEAM_NAME $url ${CI_PROJECT_NAME}-$CI_COMMIT_REF_SLUG
  except:
    refs:
      - master
      - staging
  only:
    <<: *web_deploy_common_required_changes
    variables:
      - $NOW_TOKEN
      - $NOW_TEAM_NAME
